"use client";
import { useMemo, useState } from "react";
const machines=[
 {name:"ZOE Competition",tag:"Рациональная база",price:"462 900 ₽",flow:"до 200",stock:"В наличии",tone:"sand",formats:["Кофейня","Ресторан / пекарня"],cups:["до 100","100–200"]},
 {name:"D8",tag:"Универсальная платформа",price:"от 519 500 ₽",flow:"100–300",stock:"В наличии · 21 шт.",tone:"blue",formats:["Кофейня","Ресторан / пекарня","Сеть"],cups:["100–200","200–300"]},
 {name:"D8 PRO",tag:"Независимый контроль групп",price:"от 681 300 ₽",flow:"200–500",stock:"Ограниченное количество",tone:"black",formats:["Кофейня","Сеть","Обжарщик / лаборатория"],cups:["200–300","300–500"]},
 {name:"Café Racer",tag:"Дизайн и полный контроль",price:"от 1 137 500 ₽",flow:"300+",stock:"Под заказ",tone:"red",formats:["Кофейня","Сеть","Обжарщик / лаборатория"],cups:["300–500","500+"]}
];
function Arrow(){return <span aria-hidden>↗</span>}
export default function Home(){
 const[menuOpen,setMenuOpen]=useState(false),[format,setFormat]=useState(""),[cups,setCups]=useState(""),[showResult,setShowResult]=useState(false);
 const matches=useMemo(()=>machines.filter(m=>(!format||m.formats.includes(format))&&(!cups||m.cups.includes(cups))).slice(0,3),[format,cups]);
 return <main>
  <div className="trustbar"><span>Официальный дистрибьютор Sanremo в России — BIO</span><span className="trust-contact">8 800 500-64-95 · Москва</span></div>
  <header className="header"><a className="logo" href="#top">SANREMO<small>COFFEE MACHINES</small></a><nav className={menuOpen?"nav nav-open":"nav"}><a href="#machines">Кофемашины</a><a href="#selector">Подобрать</a><a href="#solutions">Решения</a><a href="#compare">Сравнить</a><a href="#dealers">Где купить</a><a href="#service">Сервис</a></nav><button className="menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?"Закрыть":"Меню"}</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Профессиональные кофемашины · Италия</p><h1>Машина, которая<br/>соответствует<br/><em>вашему потоку</em></h1><p className="lead">Выберите Sanremo по формату бизнеса, нагрузке и меню. С актуальной РРЦ, наличием в России и понятной логикой выбора.</p><div className="hero-actions"><a className="button primary" href="#selector">Подобрать модель <Arrow/></a><a className="button ghost" href="#machines">Смотреть каталог</a></div><div className="hero-facts"><span><b>12</b> моделей в российской матрице</span><span><b>18</b> городов дилерской сети</span></div></div><div className="hero-visual"><div className="model-tag"><span>Новая платформа</span><b>D8</b><small>точность без лишней сложности</small></div><div className="availability"><i/> В наличии в России</div></div></section>
  <section className="quick-selector" id="selector"><div><p className="eyebrow">Начните с задачи</p><h2>Какая кофемашина нужна вашему бизнесу?</h2><p className="section-copy">Подбор — ориентир BIO. Учтём меню, пиковую нагрузку, число бариста и ограничения площадки.</p></div><div className="selector-fields"><label>Формат<select value={format} onChange={e=>{setFormat(e.target.value);setShowResult(false)}}><option value="">Любой формат</option><option>Кофейня</option><option>Ресторан / пекарня</option><option>Сеть</option><option>Обжарщик / лаборатория</option></select></label><label>Чашек в день<select value={cups} onChange={e=>{setCups(e.target.value);setShowResult(false)}}><option value="">Любая нагрузка</option><option>до 100</option><option>100–200</option><option>200–300</option><option>300–500</option><option>500+</option></select></label><button className="button dark" onClick={()=>setShowResult(true)}>Показать варианты <Arrow/></button>{showResult&&<div className="selector-result"><b>{matches.length?"Подходят: "+matches.map(m=>m.name).join(", "):"Нужна консультация специалиста BIO"}</b><span>{matches.length?"Ниже — РРЦ и наличие каждой модели.":"Сценарий нетипичный — поможем собрать конфигурацию."}</span></div>}</div></section>
  <section className="catalog section" id="machines"><div className="section-head"><div><p className="eyebrow">Российская матрица</p><h2>От первой машины<br/>до R&D-флагмана</h2></div><p>Не просто линейки, а доступные в России конфигурации: группы, высота, опции, цвет, РРЦ и складской статус.</p></div><div className="machine-grid">{machines.map((m,i)=><article className={"machine-card "+m.tone} key={m.name}><div className="card-top"><span>0{i+1}</span><span>{m.flow} чашек / день</span></div><div className="machine-image" aria-hidden/><div className="machine-info"><p>{m.tag}</p><h3>{m.name}</h3><div><b>{m.price}</b><span className={m.stock.includes("В наличии")?"stock yes":"stock"}>{m.stock}</span></div><a href="#dealers">Конфигурации и характеристики <Arrow/></a></div></article>)}</div></section>
  <section className="solutions section" id="solutions"><div className="section-head inverse"><div><p className="eyebrow">Не по статусу — по задаче</p><h2>Решения для<br/><em>реальной смены</em></h2></div><p>Поток, молочное меню, стабильность рецептов и простота обучения — четыре точки, с которых начинается выбор.</p></div><div className="solution-list"><article><span>01</span><h3>Первая кофейня</h3><p>ZOE Competition или D8 Basic: разумный CAPEX, понятная волюметрика, запас для роста.</p><b>до 200 чашек / день</b></article><article><span>02</span><h3>Высокий поток</h3><p>F18 MB или Café Racer: независимые системы, стабильный пар и контроль температуры.</p><b>300–500+ чашек / день</b></article><article><span>03</span><h3>Specialty и R&D</h3><p>D8 PRO или Opera: контроль групп, профилирование и повторяемость рецептов.</p><b>несколько сортов и рецептов</b></article></div></section>
  <section className="compare section" id="compare"><div className="section-head"><div><p className="eyebrow">Сравнение без лозунгов</p><h2>D8 Basic <em>или</em><br/>D8 PRO?</h2></div><p>Сравниваем конкретные исполнения и объясняем, за какие функции стоит платить именно в вашем сценарии.</p></div><div className="comparison"><div className="compare-photo"/><div className="compare-table"><div><span>Архитектура</span><b>D8 Basic</b><b>D8 PRO</b></div><div><span>Контроль групп</span><b>Общий</b><b>Независимый</b></div><div><span>Дисплей</span><b>Основная группа</b><b>На каждой группе</b></div><div><span>Лучший сценарий</span><b>Ресторан, сеть</b><b>Specialty, высокий поток</b></div><div><span>РРЦ</span><b>от 519 500 ₽</b><b>от 681 300 ₽</b></div><a className="button primary" href="#dealers">Сравнить конфигурации <Arrow/></a></div></div></section>
  <section className="case"><div className="case-copy"><p className="eyebrow">Кофейни выбирают Sanremo</p><h2>Проверка<br/><em>соревнованием</em></h2><p>D8 на Julius Meinl Barista Cup 2026. Рабочая площадка, где важны повторяемость, скорость и понятный интерфейс.</p><a href="#dealers">Смотреть российские кейсы <Arrow/></a></div></section>
  <section className="dealer section" id="dealers"><div><p className="eyebrow">Где купить</p><h2>Найдите дилера<br/>в своём городе</h2><p>Продажа, демонстрация, обучение, монтаж и сервис. Если партнёра рядом нет — заявку примет BIO.</p><div className="city-search"><input aria-label="Город" placeholder="Введите город или регион"/><button aria-label="Найти">→</button></div><div className="cities"><span>Москва · 8 партнёров</span><span>Санкт-Петербург · 4</span><span>Екатеринбург · 3</span><span>Новосибирск · 2</span></div></div><div className="map-card"><div className="map-dot d1"/><div className="map-dot d2"/><div className="map-dot d3"/><div className="dealer-mini"><b>BIO / Москва</b><span>Шоурум · Обучение · Сервис</span><a href="#contact">Показать контакты <Arrow/></a></div></div></section>
  <section className="service section" id="service"><div><p className="eyebrow">Сервис и запчасти</p><h2>Оборудование<br/>должно работать</h2></div><div className="service-cards"><article><b>01</b><h3>Запчасти по артикулу</h3><p>Поиск по модели, узлу и совместимости. Публичный складской статус без авторизации.</p><a href="#contact">Найти запчасть <Arrow/></a></article><article><b>02</b><h3>Подготовка к монтажу</h3><p>Вода, фильтрация, электрика, слив и пространство — чек-лист до приезда инженера.</p><a href="#contact">Получить чек-лист <Arrow/></a></article><article><b>03</b><h3>Сервисная сеть</h3><p>Гарантийные и постгарантийные работы с понятной зоной ответственности.</p><a href="#contact">Найти сервис <Arrow/></a></article></div></section>
  <section className="cta" id="contact"><p className="eyebrow">Следующий шаг</p><h2>Соберём конфигурацию<br/><em>под вашу задачу</em></h2><p>Оставьте задачу, регион и срок запуска. Специалист BIO уточнит нагрузку и соединит с подходящим дилером.</p><div><a className="button primary" href="mailto:info@sanremomachines.ru">Получить консультацию <Arrow/></a><a className="button cta-ghost" href="tel:+78005006495">8 800 500-64-95</a></div></section>
  <footer><a className="logo foot-logo" href="#top">SANREMO<small>COFFEE MACHINES</small></a><div><b>Каталог</b><a href="#machines">Кофемашины</a><a href="#selector">Подбор</a><a href="#compare">Сравнение</a></div><div><b>Поддержка</b><a href="#dealers">Дилеры</a><a href="#service">Сервис</a><a href="#service">Запчасти</a></div><div><b>BIO</b><span>Официальная дистрибуция<br/>Sanremo в России</span><span>© 2026 BIO</span></div></footer>
 </main>
}
